on:
  # Triggers the workflow on push or pull request events but only for the master branch
  workflow_dispatch:

jobs:
  deploy-redirect-sec-engineer:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout base repo
        uses: actions/checkout@v2

      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "deploy"
          cdk_args: "--require-approval never"
          actions_comment: false
        env:
          DOMAIN: "sec-engineer.sh"
          REDIRECT: "scharitzer.io"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-central-1"
